### ISSUE TITLE
pnpm option

### ISSUE THREAD

**Issue by brettz9** [sapegin/mrm#114]
Hi,

First let me thank you for what looks like is going to be an incredibly useful tool.

In finding my desktop hijacked by an ever-growing number of repos/packages (something your project will likely only encourage), I am drawn to pnpm for saving space in avoiding immensely redundant storage.

Would you consider adding it as an option for installs, as you do for yarn?

I'd ideally like to see this configurable such that other tasks, like say the eslint task, would use pnpm instead of npm, but if it t least enters the API, it'd be encouraging to know I can make tasks to use it.

**Comment by sapegin** [comment]
The question is how we're going to switch to `pnpm` because right now it's automated based on the presence of either `package-lock.json` or `yarn.lock` files. Can we do this for pnpm?

There's already the `yarn` options on the `install()` method but it isn't used from default tasks. However, it'd be a good idea to add an option to the `package` task to create the correct lock file for the desired package manager so other tasks could use the right package manager to install packages.

**Comment by brettz9** [comment]
> The question is how we're going to switch to `pnpm` because right now it's automated based on the presence of either `package-lock.json` or `yarn.lock` files. Can we do this for pnpm?

Yeah, pnpm creates its own lock files too (`pnpm-lock.yaml`).

> There's already the `yarn` options on the `install()` method but it isn't used from default tasks. However, it'd be a good idea to add an option to the `package` task to create the correct lock file for the desired package manager so other tasks could use the right package manager to install packages.

SGTM.
