### ISSUE TITLE
use `npx mrm lint-staged`  but `Cannot configure lint-staged`

### ISSUE THREAD

**Issue by innerWang** [sapegin/mrm#41]
I was trying to use `create-react-app` create a react-demo with add eslint & prettier config in the `package.json`. When I run the command `npx mrm lint-staged` failed and show error as `Cannot configure lint-staged, only ESLint, stylelint or custom rules are supported.`

After checking the code, I found there is an if statement `pkg.get('devDependencies.prettier') && !pkg.get('devDependencies.eslint-plugin-prettier')`. In my case, I have both `prettier` and `eslint-plugin-prettier` installed, which casued a failure. 

Does anyone have the same issue or have a solution, thanks

- OS : MacOS

- my package.json config:
```js
"devDependencies": {
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.4.0",
    "eslint-plugin-prettier": "^3.1.1",
    "node-sass": "^4.12.0",
    "prettier": "^1.18.2"
  }
```

**Comment by sapegin** [comment]
Please be more careful with choosing words next time. This is an open source project, it does whatever contributors made it to do. If you need a new feature, feel free to send a pull request.

**Comment by sapegin** [comment]
In your case you need to have a `eslint` dependency in your project because that's how you actually run Prettier.

The condition, you're referring to, is to run `prettier` separately, but this assumes you're not using ESLint Prettier plugin.

Removing the `eslint-plugin-prettier` could be another option (better in my opinion because I think the developer experience with this plugin is quite annoying). But you'd still want to add `eslint` dependency to run ESLint with lint-staged.
