### ISSUE TITLE
Interactive mode is not clear

### ISSUE THREAD

**Issue by lnmunhoz** [sapegin/mrm#77]
I spent some time trying to figure out how to make inquirer prompt my parameters with no success, until I dive into the code to see that is expecting a `--interactive` flag. I feel that's not very intuitive since I am defining parameters in my task I feel it should work by default.

Also it could be listing in the docs that you have to explicitly pass `--interactive` to get the prompt.

Happy to help to improve this tool, it's awesome and have a lot of potential!

**Comment by sapegin** [comment]
Usually, you already have all the necessary parameters in the config file, so asking again every time you run a task would be annoying. That's why it's not interactive by default. And you don't define parameters _for interactive_ mode but for both modes.

Feel free to make the docs more clear though 👾

**Comment by lnmunhoz** [comment]
Gotcha, I will experiment more with the library and edit the docs accordingly. Thanks 👍
